AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Quiz Backend - Prod - FastAPI on Lambda

Parameters:
  MongoAuthCredentials:
    Type: String
    Description: Credentials to connect with MongoDB

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "QuizBackendProd"
      CodeUri: ../app
      Handler: main.handler
      Runtime: python3.9
      Environment:
        Variables:
          MONGO_AUTH_CREDENTIALS: !Ref MongoAuthCredentials
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
