AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Quiz Backend - Staging - FastAPI on Lambda

Parameters:
  MongoAuthCredentials:
    Type: String
    Description: Credentials to connect to the MongoDB instance

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "QuizBackendStaging"
      CodeUri: ../app
      Handler: main.handler
      Runtime: python3.9
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          MONGO_AUTH_CREDENTIALS: !Ref MongoAuthCredentials
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Role: !GetAtt LambdaExecutionRole.Arn

  Api:
    Type: AWS::Serverless::HttpApi

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: 'Allow'
                Action:
                  - 'sns:Publish'
                Resource: 'arn:aws:sns:ap-south-1:*:*'

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
