name: CI

on:
  pull_request:
  push:
    branches: [main, release]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12 for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Show Python version (debug)
        run: python --version
      - uses: pre-commit/action@v3.0.1

  unit-tests:
    name: Test cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: 5.0

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Test Cases
        env:
          MONGO_AUTH_CREDENTIALS: mongodb://localhost:27017
        # command to run tests and generate coverage metrics
        run: |
          coverage run --rcfile=.coveragerc -m pytest
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
